/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.JOptionPane;
import modelo.Ferramenta;
import dao.FerramentaDAO;

/**
 *
 * @author User
 */
public class frmCadastroFerramenta extends javax.swing.JFrame {

    private Ferramenta objetoFerramenta;
    private FerramentaDAO ferramentaDAO;

    /**
     * Creates new form frmGerenciaAmigos
     */
    public frmCadastroFerramenta() {
        initComponents();
        this.objetoFerramenta = new Ferramenta();
        this.ferramentaDAO = new FerramentaDAO();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTFMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFCusto = new javax.swing.JTextField();
        JBCancelar2 = new javax.swing.JButton();
        JBCadastrar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Ferramentas");
        setMinimumSize(new java.awt.Dimension(590, 365));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Cadastrar Ferramenta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(167, 27, 248, 44);
        getContentPane().add(JTFNome);
        JTFNome.setBounds(60, 123, 205, 26);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 127, 50, 18);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(291, 127, 50, 18);
        getContentPane().add(JTFMarca);
        JTFMarca.setBounds(345, 123, 205, 26);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Preço de Custo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 208, 110, 18);
        getContentPane().add(JTFCusto);
        JTFCusto.setBounds(120, 210, 423, 26);

        JBCancelar2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        JBCancelar2.setForeground(new java.awt.Color(255, 0, 0));
        JBCancelar2.setText("Cancelar");
        JBCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelar2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar2);
        JBCancelar2.setBounds(360, 280, 110, 40);

        JBCadastrar2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        JBCadastrar2.setForeground(new java.awt.Color(51, 255, 51));
        JBCadastrar2.setText("Cadastrar");
        JBCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCadastrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBCadastrar2);
        JBCadastrar2.setBounds(90, 280, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelar2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBCancelar2ActionPerformed

    private void JBCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCadastrar2ActionPerformed
        try {
            String nome = "";
            String marca = "";
            double custo = 0.0;

            if (this.JTFNome.getText().length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.JTFNome.getText();
            }
            if (this.JTFMarca.getText().length() < 2) {
                throw new Mensagens("Marca deve conter ao menos 2 caracteres.");
            } else {
                marca = this.JTFMarca.getText();
            }
            if (this.JTFCusto.getText().length() <= 0) {
                throw new Mensagens("Custo deve ser um número positivo.");
            } else {
                custo = Double.parseDouble(this.JTFCusto.getText());
            }

            // envia os dados para o Controlador cadastrar
            Ferramenta novaFerramenta = new Ferramenta();
            novaFerramenta.setNome(nome);
            novaFerramenta.setMarca(marca);
            novaFerramenta.setCusto(custo);

            FerramentaDAO ferramentaDAO = new FerramentaDAO();
            boolean inserido = ferramentaDAO.inserirFerramentaBD(novaFerramenta);

            if (inserido) {
                JOptionPane.showMessageDialog(null, "Ferramenta Cadastrada com Sucesso!");
                // limpa campos da interface
                this.JTFNome.setText("");
                this.JTFMarca.setText("");
                this.JTFCusto.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar ferramenta.");
            }

            // Exibindo no console a ferramenta cadastrada
            System.out.println(ferramentaDAO.getListaFerramenta().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número válido.");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_JBCadastrar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastroFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCadastrar2;
    private javax.swing.JButton JBCancelar2;
    private javax.swing.JTextField JTFCusto;
    private javax.swing.JTextField JTFMarca;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
